In [1]:
import pandas as pd
from mopac_batch_runner import run_mopac_batch

In [2]:
df = pd.read_csv('./datasets/12k_pfas_canonical.csv', sep=',')


df_100 = df.head(100)

In [3]:
df_100.head()

,compound_id,SMILES,canonical_SMILES
0,100016-68-0,FC(F)(OC(\F)=C(\F)F)C(F)(F)OC(F)(C(=O)OC)C(F)(F)F,COC(=O)C(F)(OC(F)(F)C(F)(F)OC(F)=C(F)F)C(F)(F)F
1,1000-28-8,FC(C(F)(F)OCC(F)(F)C(F)(F)F)C(F)(F)F,FC(C(F)(F)F)C(F)(F)OCC(F)(F)C(F)(F)F
2,1000339-60-5,ClCc1ccc(cc1F)C(F)(F)F,Fc1cc(C(F)(F)F)ccc1CCl
3,1000509-29-4,FC(F)(C(F)(F)CCN)C(F)(F)F,NCCC(F)(F)C(F)(F)C(F)(F)F
4,1000572-70-2,FC(F)(F)c1ccc(cc1CCO)C(F)(F)F,OCCc1cc(C(F)(F)F)ccc1C(F)(F)F

In [4]:
results = run_mopac_batch(
    df=df_100,
    smiles_col="canonical_SMILES",
    id_col="compound_id",
    keywords="PM7 GEO-OK",
    workdir="mopac_jobs",
    overwrite=True,
    max_workers=6,
    timeout=900,
)

print(results[["compound_id", "status", "duration_s"]])

     compound_id   status  duration_s
0    100016-68-0  success       2.554
1      1000-28-8  success       0.614
2   1000339-60-5  success       3.429
3   1000509-29-4  success       0.466
4   1000572-70-2  success       0.612
..           ...      ...         ...
95  1006486-98-1  success       0.866
96  1006614-95-4  success       1.960
97  1006627-74-2  success       1.424
98   100664-15-1  success      16.334
99   100700-41-2  success      12.141

[100 rows x 3 columns]

In [5]:
results[results['arc_file'].isna()]#.to_csv('failed_runs.csv')

,compound_id,smiles,status,mop_file,out_file,arc_file,error_message,return_code,duration_s
72,100482-51-7,OC(C=C(C(F)(F)F)C(F)(F)F)c1cccc(Cl)c1,success,C:\Users\macie\Documents\GitHub\smi_to_mop\mop...,C:\Users\macie\Documents\GitHub\smi_to_mop\mop...,NaN,None,0,21.049